# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ravi Teja Gangineni
email: rteja7228@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack development is my final goal as the days progress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raviteja.gangineni.com" # the base hostname & protocol for your site
twitter_username: rteja91
github_username:  rteja91

# Build settings
markdown: kramdown
